version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: parenting-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=P@!!w0rd@555
      - MYSQL_DATABASE=parenting_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/mysql-init/Dump20251104.sql:/docker-entrypoint-initdb.d/Dump20251104.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: parenting-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: parenting-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  default:
    name: parenting-net

volumes:
  db_data:
